### ISSUE TITLE
Inquiry about LICENSE

### ISSUE THREAD

**Issue by yogeshmurthy93** [israel-dryer/ttk-arc-clone#1]
Dear project maintainer(s),

This is impressive work. 

Is there any possibility of using this code in a commercial application? It will be a python application packaged as an executable and distributed to customers. 

I do not see a license in the repo. Since it is a python version of the Arc ttk theme, does the [GPL3 license](https://github.com/cjrh/ttk-themes/blob/master/LICENSE) from the original repo apply here? 

I appreciate your time and look forward to your response. Thank you for your work on this project and for considering my inquiry.

**Comment by israel-dryer** [comment]
Yes. You are free to use.

**Comment by yogeshmurthy93** [comment]
Thank you :)
